### ISSUE TITLE
Add `platform-wildcards`

### ISSUE THREAD

**Issue by cgwalters** [cgwalters/cargo-vendor-filterer#23]
Right now the `platforms` is basically an API we need to commit to, but I think most users would want:

`platform-wildcards: ["*-linux-gnu", "wasm32-*"]`

for example.  In particular I discovered over in https://github.com/coreos/coreos-installer/pull/894 that coreos-installer actually has s390x-specific dependencies.

**Comment by jlebon** [comment]
Bikeshed: we could reuse the `platforms` key but detect the glob character.
